var sides = [
  'Stir-fried Vegetables',
  'Red Beans and Rice',
  'Asparagus Rotini Pasta',
  'Lemon Risotto',
  'Basic Baked Risotto',
  'Broccoli, Bean and Crispy Sage Orecchiette',
  'Crispy Pea and Mint Risotto Balls',
  'Pancetta, Sweet Potato and Sage Baked Risotto',
  'Ricotta and Parmesan Fritters',
  'Coconut Rice',
  'Sausage Stuffed Mushrooms',
  'Tomato Vegetable Casserole',
  'Parmesan Peas',
  'Creamed Pearl Onions',
  'Whipped Root Vegetables',
  'Butternut Squash Mac and Cheese',
  'Sweet Potato Poutine',
  'Cuban Black Beans',
  'Steamed Mussels in Garden Tomato Sauce',
  'Baked Bean Falafel',
  'Quick Pickles'
];

var mainDishes = [
  'Frito Pie',
  'Soy-glazed Chicken',
  'Roasted Cornish Game Hens',
  'Red Lentil Curry',
  'Penne a la Carbonara',
  'Green Chile Chicken Enchilada Casserole',
  'Slow-cooker Italian Beef',
  'Southwestern Black Bean Soup',
  'Lemon Garlic Shrimp',
  'Ginger Chili Salmon with Noodles',
  'Salmon with Fennel',
  'Authentic Thai Green Curry',
  'Summer Squash and Basil Pasta',
  'Green Goddess Buddha Bowl',
  'Lemongrass and Coriander Grilled Chicken Skewers',
  'Chicken Pad Thai',
  'Classic Chicken Laska',
  'Chicken and Herb Risoni',
  'Coconut and Lime Roasted Chicken',
  'Grandma\'s Baked Eggplant Parmesan',
  'Pasta Puttanesca'
];

var desserts = [
  'Butter Spritz Cookies',
  'Figgy Pudding',
  'Chocolate Truffle Cookies',
  'Hibiscus Pavlova with Lemon-Hibiscus Cream',
  '3-Ingredient Flourless Chocolate Cake',
  'French Macarons',
  'Strawberry Cucumber Ice Pops',
  'Coconut Rice',
  'Homemade Dole Whip',
  'Country Blueberry Pie',
  'Sticky Toffee Pecan Pumpkin Pie',
  'Blueberry Puff Pastry Galette',
  'Banana Layer Cake',
  'Blackberry Cheesecake Pots',
  'Chocolate Meringue Cake',
  'Banana Tarte Tatin & Malai Ice Cream'
];
